In [1]:
import pandas as pd

In [15]:
df = pd.read_excel(
    "C:/Users/osmin/Documents/Projects/trabajo/Reports_generator/Archivos/ORDENES AZTEC SMI 2024.xlsm",
    sheet_name="ORDENES",
    header=None,
    skiprows=1
    )

df.columns

c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,
       ...
       16363, 16364, 16365, 16366, 16367, 16368, 16369, 16370, 16371, 16372],
      dtype='int64', length=16373)

In [24]:
# needed_columns = [".", "JOB", "Unnamed: 16364"]
orders_columns = [0, 1, 2, 3, 10]

orders_df = df.iloc[:, orders_columns]

orders_df.columns = ["STATUS", "ORDER_ID", "DATE", "CUSTOMER", "SHEETS ORDER"]


orders_df["DATE"] = pd.to_datetime(orders_df["DATE"], errors="coerce")

orders_df = orders_df[orders_df["DATE"].notna()]

# orders_df.head(97)
# print(orders_df.iloc[96]["DATE"])
orders_df

C:\Users\osmin\AppData\Local\Temp\ipykernel_4064\2460279892.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_df["DATE"] = pd.to_datetime(orders_df["DATE"], errors="coerce")

,STATUS,ORDER_ID,DATE,CUSTOMER,SHEETS ORDER
0,FINISHED,190616,2019-10-23,FIJACIONES ANTICORROSIVAS - CANCELADA,603.97
1,FINISHED,200171,2020-03-05,ELECTRO CRAFT,23.00
2,FINISHED,200535,2020-10-28,HAWK CAMCAR,180.00
3,FINISHED,200622,2020-12-16,LELAND,250.00
4,FINISHED,210000,2021-01-04,INFRA,315.00
...,...,...,...,...,...
2641,OPEN,250185,2025-03-24,ETANCO,687.00
2642,OPEN,250186,2025-03-24,ETANCO,125.00
2643,OPEN,250187,2025-03-24,OUTS MARCO,185.37
2644,OPEN,250188,2025-03-24,OUTS MARCO,53.45
2645,OPEN,250189,2025-01-22,LELAND,2000.00

In [26]:
df_vulcanizado = pd.read_excel('C:/Users/osmin/Documents/Projects/trabajo/Reports_generator/Archivos/ORDENES AZTEC SMI 2024.xlsm',
                            sheet_name="VULCANIZADO"
                            
                            )

df_vulcanizado.head()

c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,DATE,JOB,CLIENTE,PART NUMBER,LAMINAS\n ORDEN,BATCH METAL,GA,METAL,MEDIDA DE LAMINA,HEAT DE METAL,...,TURNO,SHEETS,# TARIMA,OBSERVACIONES,MAQ T,VELOCIDAD,\nCAJAS,SCRAP/SHEETS 18X72,QTY TOTAL VULCANIZADO,NOTAS
0,2022-09-01 00:00:00,190616,FIJACIONES ANTICORROSIVAS - CANCELADA,GJZ125025X,603.97,132905,20,GALVANIZED,"COIL 9""",NO HEAT,...,1.0,NaN,NaN,.188 FOAM BLACK,18,00:04:00,NaN,6.48,6.48,SCRAP - MATERIAL QUE NO SE REPORTO EN SU MOMENTO
1,2022-06-22 00:00:00,200622,LELAND,ANE054024X,250,1193500-A,.032,ALUMINUM,"COIL 9""",13118,...,1.0,46.71,NaN,.059 EPDM BLACK-ECO,7,00:06:20,NaN,NaN,46.71,MAT QUE NO SE REPORTO EN SU MOMENTO-PARA CUDRA...
2,2022-06-22 00:00:00,200622,LELAND,ANE054024X,250,1193500-A,.032,ALUMINUM,"COIL 9""",13118,...,1.0,8.22,NaN,.059 EPDM BLACK-ECO,7,00:06:20,NaN,NaN,8.22,SCRAP
3,2021-02-16 00:00:00,210000,INFRA,GJE072041C,315,195658-A,20,GALVANIZED,"COIL 9""",NaN,...,2.0,40.49,1,.059 EPDM BLACK,7,07:10:00,8,NaN,40.49,NaN
4,2021-02-17 00:00:00,210000,INFRA,GJE072041C,315,195653-A,20,GALVANIZED,"COIL 9""",NaN,...,1.0,15.18,NaN,.059 EPDM BLACK,3,07:20:00,3,NaN,15.18,C/B

In [29]:
vulc_columns = ["DATE", "JOB", "QTY TOTAL VULCANIZADO"]

vulcan_df = df_vulcanizado.loc[:, vulc_columns]

vulcan_df.columns = ["DATE", "ORDER_ID", "QTY_TOTAL_VULCANIZADO"]

vulcan_df["DATE"] = pd.to_datetime(vulcan_df["DATE"], errors="coerce")

vulcan_df = vulcan_df[vulcan_df["DATE"].notna()]

vulcan_df

            DATE ORDER_ID  QTY_TOTAL_VULCANIZADO
0     2022-09-01   190616                   6.48
1     2022-06-22   200622                  46.71
2     2022-06-22   200622                   8.22
3     2021-02-16   210000                  40.49
4     2021-02-17   210000                  15.18
...          ...      ...                    ...
17608 2025-03-24   250053                   5.67
17609 2025-03-24   240651                  73.66
17610 2025-03-24   240651                   8.93
17611 2025-03-24   240568                  30.95
17612 2025-03-24   240568                   7.14

[17602 rows x 3 columns]

In [30]:
files = [
    (
        "./Archivos/LAMINAS GALVANIZADOS RELACION DE SCRAP EN CONTENEDORES METAL-HULE.xlsm",
        "RELACION GALVANIZADO",
    ),
    (
        "./Archivos/LAMINAS ALUMINIOS RELACION DE SCRAP EN CONTENEDORES METAL-HULE.xlsm",
        "RELACION ALUMINIO",
    ),
    (
        "./Archivos/LAMINAS STAINLESS RELACION DE SCRAP EN CONTENEDORES METAL-HULE.xlsm",
        "RELACION STAINLESS",
    ),
]

dataframes = []

# Columnas necesarias
columnas_necesarias = ["Fecha", "# de Orden", "SCRAP/SHT"]

# Leer cada archivo y su hoja especÃ­fica
for archivo, hoja in files:
    df = pd.read_excel(archivo, sheet_name=hoja, header=9)

    # Filtrar solo las columnas necesarias (verifica los nombres exactos)
    df = df[columnas_necesarias]

#     # Agregar el DataFrame a la lista
    dataframes.append(df)

# # Concatenar todos los DataFrames en uno solo
df_final = pd.concat(dataframes, ignore_index=True)
df_final

c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

                    Fecha # de Orden  SCRAP/SHT
0     2022-06-20 00:00:00    GAYLORD        NaN
1     2022-06-17 00:00:00     210076   0.659703
2     2022-06-20 00:00:00     210633   0.531350
3     2022-06-21 00:00:00     210633   0.850159
4     2022-06-21 00:00:00     210633   0.265675
...                   ...        ...        ...
4672  2025-03-21 00:00:00     250061   1.216893
4673  2025-03-21 00:00:00     250073   1.054111
4674  2025-03-21 00:00:00     240718   4.055822
4675  2025-03-24 00:00:00   GRIPPERS        NaN
4676  2025-03-24 00:00:00     240395   3.003003

[4677 rows x 3 columns]

In [21]:
files = [
    ("./Archivos/OMBLIGOS ALUMINIOS RELACION DE SCRAP EN CONTENEDORES METAL-HULE.xlsm","RELACION ALUMINIO"),
    ("./Archivos/OMBLIGOS GALVANIZADOS RELACION DE SCRAP EN CONTENEDORES METAL-HULE.xlsm","RELACION GALVANIZADO")
]

dataframes = []

needed_columns = [1,2,16]

for file,sheet in files:
    df = pd.read_excel(file,sheet_name=sheet,header=9)

    df = df.iloc[:,needed_columns]
    
    df.columns = ["Fecha","# de Orden","SCRAP/SHT"]

    dataframes.append(df)

final_df = pd.concat(dataframes,ignore_index=True)
final_df

c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
c:\Users\osmin\Documents\Projects\trabajo\Reports_generator\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

                    Fecha # de Orden  SCRAP/SHT
0     2022-07-14 00:00:00    GAYLORD        NaN
1     2022-07-14 00:00:00     TARIMA        NaN
2     2022-07-14 00:00:00      BOLSA        NaN
3     2022-07-13 00:00:00     210798        NaN
4     2022-07-13 00:00:00     210757        NaN
...                   ...        ...        ...
7914  2025-03-24 00:00:00     240626        NaN
7915  2025-03-24 00:00:00     240616      552.0
7916  2025-03-24 00:00:00     240626        NaN
7917  2025-03-25 00:00:00     250027      594.0
7918  2025-03-25 00:00:00     250027        NaN

[7919 rows x 3 columns]